# Generated by Django 3.2.17 on 2023-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('telpnum', models.CharField(max_length=128, verbose_name='邮箱')),
                ('img', models.CharField(max_length=128, verbose_name='头像')),
            ],
        ),
    ]
